name: Update Tenable IP Prefixes

on:
  schedule:
    - cron: '0 7 * * *' # Daily at 7 AM UTC
  workflow_dispatch:

jobs:
  update-ip-prefixes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch and format Tenable IP prefixes
        run: |
          curl -s https://docs.tenable.com/ip-ranges/data.json > data.json
          echo "# Tenable IP Prefixes" > docs/tenable-ip-prefixes.md
          echo "" >> docs/tenable-ip-prefixes.md
          echo "_Last updated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')_" >> docs/tenable-ip-prefixes.md
          echo "" >> docs/tenable-ip-prefixes.md
          jq -r '.prefixes[].ip_prefix' data.json | sort | uniq | sed 's/^/- /' >> docs/tenable-ip-prefixes.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/tenable-ip-prefixes.md
          git commit -m "Daily update of Tenable IP prefixes"
          git push
